import { Dimensions, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        width: "100%",
        height: "100%",
    },
    bottomContainer: {
        height: Dimensions.get("window").height*0.10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginRight: 20,
        marginLeft: 20,
    },
    bottomText: {
        fontSize: 20,
        fontWeight: "bold",
        fontFamily: "monospace",
        color: "grey",
    },
    syncButton: {
        backgroundColor: "orange",
        height: 40,
        width: 40,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 20,
        borderColor: "lightgrey",
        borderWidth: 2,
    },
    barButton: {
        backgroundColor: "orange",
        height: 40,
        width: 40,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 20,
        borderColor: "lightgrey",
        borderWidth: 2,
    },
    goButton: {
        position: "absolute",
        bottom: Dimensions.get("window").height*0.10 + 10,
        backgroundColor: "orange",
        width: 80,
        height: 80,
        alignItems: "center",
        justifyContent: "center",
        left: Dimensions.get("window").width/2 - 40,
        borderRadius: 40,
        borderWidth: 3,
        borderColor: "lightgrey"
    },
    goText: {
        fontSize: 24,
        fontWeight: "bold",
        color: "white",
        fontFamily: "monospace",
    },
    topIcons: {
        zIndex: 10,
        position: "absolute",
        top: 50,
        right: "5%",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        width: "90%",
    },
    menuButton: {
        backgroundColor: "white",
        width: 50,
        height: 50,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 25,
        borderColor: "lightgrey",
        borderWidth: 2,
    },
    searchButton: {
        backgroundColor: "white",
        width: 50,
        height: 50,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 25,
        borderColor: "lightgrey",
        borderWidth: 2,
    }
});